# docker-compose.yml - Development environment
version: "3.8"

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - /app/venv # Exclude venv from volume mount
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - DATABASE_URL=mysql+pymysql://sertifikatet:password@db:3306/sertifikatet_dev
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - db
      - redis
    command: flask run --host=0.0.0.0 --port=8000

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: sertifikatet_dev
      MYSQL_USER: sertifikatet
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  test:
    build: .
    environment:
      - TESTING=1
      - DATABASE_URL=sqlite:///:memory:
      - REDIS_URL=redis://redis:6379/15
    depends_on:
      - redis
    command: pytest tests/ -v
    profiles:
      - test

volumes:
  mysql_data:
  redis_data:
